version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
      POSTGRES_USER : ${DEFAULT_DATABASE_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 5433:8080
    depends_on:
      - postgres