# Generated by Django 4.2.5 on 2023-09-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True)),
                ('tutor', models.CharField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('esporadico', 'esporadico'), ('assinatura', 'assinatura'), ('degustacao', 'degustacao'), ('cancelou', 'cancelou'), ('faleceu', 'faleceu'), ('parceria', 'parceria')])),
                ('cpf', models.CharField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('como_chegou', models.CharField(blank=True, choices=[('instagram', 'instagram'), ('facebook', 'facebook'), ('indicacao', 'indicacao'), ('', '')])),
                ('endereco', models.CharField(blank=True)),
                ('email', models.CharField(blank=True)),
                ('bairro', models.CharField(blank=True)),
                ('cidade', models.CharField(blank=True)),
                ('estado', models.CharField(blank=True)),
                ('cep', models.CharField(blank=True)),
                ('ddd', models.CharField(blank=True)),
                ('telefone', models.CharField(blank=True)),
                ('raca', models.CharField(blank=True)),
                ('genero', models.CharField(blank=True, choices=[('macho', 'macho'), ('femea', 'femea')])),
                ('peso', models.CharField(blank=True)),
                ('receita', models.CharField(blank=True)),
                ('aniversario', models.CharField(blank=True)),
                ('assinatura', models.CharField(blank=True)),
                ('gramas_por_dia', models.CharField(blank=True)),
                ('kg_mes', models.CharField(blank=True)),
                ('valor_kg', models.CharField(blank=True)),
                ('valor_assiinatura_c_frete', models.CharField(blank=True)),
                ('valor_assinatura_s_frete', models.CharField(blank=True)),
                ('valor_frete', models.CharField(blank=True)),
            ],
            options={
                'db_table': 'table_clientes',
                'unique_together': {('cliente', 'tutor')},
            },
        ),
    ]
